; Electro — Tara Robot Firmware
; Board: ESP32 Dev Module
; Display: ST7735 128x160 V1.1 (SPI)
;
; Flash:          pio run -e robot -t upload
; Serial monitor: pio device monitor

[env]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
upload_port   = /dev/cu.usbserial-0001
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4
    adafruit/Adafruit GFX Library@^1.11.9
    http://pi-nest.local:30600/api/files/log4c/log4c/2.3.0/log4c.zip
    http://pi-nest.local:30600/api/files/wifi4h/wifi4h/1.0.1/wifi4h.zip
    http://pi-nest.local:30600/api/files/reg4h/reg4h/1.0.0/reg4h.zip
    http://pi-nest.local:30600/api/files/ota4h/ota4h/2.0.0/ota4h-2.0.0.zip
    http://pi-nest.local:30600/api/files/socket4h/socket4h/1.0.1/socket4h-1.0.1.zip
    http://pi-nest.local:30600/api/files/touch-me/touch-me/1.2.0/touch-me.zip

[env:robot]
build_flags =
    -DDEVICE_NAME='"Tara"'
    -DDEVICE_TYPE='"tara-robo"'
    -DFW_VERSION='"1.8.5"'
    -DPROV_WIFI_SSID='"YourSSID"'
    -DPROV_WIFI_PASS='"YourPass"'
    -DPROV_SERVER_HOST='"pi-nest.local"'
    -DPROV_SERVER_PORT='"3001"'
