name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

jobs:
  compile:
    name: Compile firmware
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Inject Pocket token
        run: |
          sed -i 's|?token=[a-zA-Z0-9_]*|?token=${{ secrets.POCKET_API_KEY }}|g' platformio.ini

      - name: Inject version
        run: |
          VERSION=$(cat VERSION)
          sed -i "s/-DFW_VERSION='\"[^\"]*\"'/-DFW_VERSION='\"${VERSION}\"'/" platformio.ini

      - name: Compile robot firmware
        run: pio run -e robot
